### ISSUE TITLE
ivoatex link: set to specific commit

### ISSUE THREAD

**Issue by brianmajor** [ivoa-std/GMS#21]
Does anyone know how to make the `ivoatex` link go to HEAD rather than a specific commit (as it is currently set)?  I'm not sure where this link is managed.  There are updates to the bibliography that I need to pull in.

**Comment by mbtaylor** [comment]
I was waiting for somebody more expert than me to answer this, but in their absence... A module points at a specific commit of its external repository by design, so that the code state is well-defined rather than at the mercy of where your HEAD happens to be at.

So you can't get it to point at HEAD, you need to decide which named module commit you want to point at, and make a corresponding local commit that updates that value.  I can't remember off the top of my head the exact magic to do that, but probably you can work it out.

**Comment by brianmajor** [comment]
Thanks Mark, that was enough info to get me going.  I found that, in your clone, the submodule is like any other git clone but in a directory.  So, I was able to simply navigate into `ivoatex`, pull from master,and commit the changes to the submodule.  So in that sense you are right--the submodule is always a snapshot of some commit from the repository.
